version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE}
    volumes:
      - .:/app
    container_name: go-todo-api-dev
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - database
  database:
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
  pg_admin:
    image: dpage/pgadmin4:2022-07-25-1
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_DEFAULT_PORT}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_DEFAULT_PORT}:${PGADMIN_DEFAULT_PORT}"
    depends_on:
      - database
volumes:
  database-data:
  pgadmin-data:
